version: '3'
services:
  php:
    build:
      context: ./php
      dockerfile: ./Dockerfile-php
    image: app-php
    container_name: app-php
    ports:
      - 32770:80
    environment:
      MYSQL_SERVICE: myDB
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./php/src:/var/www/html/
      - ./php/myconfig.ini:/usr/local/etc/php/conf.d/myconfig.ini
    links:
      - mysql:myDB
    depends_on:
      - mysql
  mysql:
    build:
      context: ./mysql
      dockerfile: ./Dockerfile-mysql
    image: app-mysql
    container_name: app-mysql
    volumes:
      - ./mysql/.db:/var/lib/mysql
    command: ['--innodb_use_native_aio=0','--log_bin_trust_function_creators=1']
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: America/Panama
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 32771:8080
    environment:
      ADMINER_DESIGN: ${ADMINER_DESIGN}
    links:
      - mysql:myDB
    depends_on:
      - mysql
